### ISSUE TITLE
Font style formatting never applied to first new paragraph

### ISSUE THREAD

**Issue by AshenColors** [greenwyrt/plover2CAT#10]
v:  2.1.0
OS: Windows 11

Steps to reproduce: 
1. Create a new transcript.
2. Change the font and press 'Modify' to apply the style.
3. Mash some steno keys and observe that the font is not what was selected.
4. Press Modify again to apply the style, changing the paragraph font.
5. Asterisk backspace all of the paragraph.
6. Mash some more steno keys and observe that the font has reverted to the pre-Modify default font.

The upshot of this is that on a new transcript file, or after starting the first paragraph over, the current style is never applied. The desired behavior is for those font settings to be applied to the first new text in the document unless set otherwise. This can be fixed in post-editing, but since I use font size to make seeing the transcript and paper tape easier, it causes some usability issues. I'm not entirely sure how the formatting system works still, so I've been dragging my feet on actually attempting to make a working patch.

**Comment by greenwyrt** [comment]
The styling system needs to be redone, it's on my todo list. 

The system as it is now, someone changes parameters in a style, it's not possible to undo them and we can only undo what style is applied to a paragraph only if it had an existing style. It's a bit of a mess.

If the paragraph style doesn't match the set style, the quick fix is do Styling -- Refresh Editor.

I'm going to leave this open to remind myself.
